### ISSUE TITLE
Why avoid joins?

### ISSUE THREAD

**Issue by wald-tq** [juan7792/VideoGamesDiary#1]
https://github.com/juan7792/VideoGamesDiary/blob/e42ed1591c858dd1f6d92dcd4c7b47b1380baf38/video_game_diary/video_game_diary/queries.cpp#L157

Why do you want to avoid joins?

**Comment by juan7792** [comment]
This was just a reminder to not forget to come back to this in a later moment. Honestly, at that very moment I just wanted to move forward with the app instead of doing the small task of thinking how the JOIN would look like :). Thanks for pointing it out!
