### ISSUE TITLE
Game name should be already in database

### ISSUE THREAD

**Issue by wald-tq** [juan7792/VideoGamesDiary#2]
https://github.com/juan7792/VideoGamesDiary/blob/e42ed1591c858dd1f6d92dcd4c7b47b1380baf38/video_game_diary/video_game_diary/queries.cpp#L252

Why do I have to type the name again? It should be already in the database.

**Comment by juan7792** [comment]
As in the last comment, I wanted to move forward with the app itself, not the database, so I am keeping this for further improvements. With a JOIN I wouldn't have to type in again the name when viewing the games list, but this was simply a dragged issue for skipping the JOIN before :). I am glad and appreciate that you took the time to take a look to the code!

**Comment by wald-tq** [comment]
Your app is tightly coupled to your database. You designed your database so that you can avoid the join. Now you have to supply the name of the game which would be otherwise not necessary. Not to mention that it is error prone, what if you get a typo in the name?

Another thing is that you should separate your data input from your database logic. There should be no calls to `getline` in your database logic, so you could reuse the data access and maybe create a graphical interface next...

**Comment by juan7792** [comment]
Thank you for the tips, Wald. I will surely be including your recommendation in my further work :). Cheers!
